[package]
name = "symjit-bridge"
version = "2.13.0"
edition = "2021"

[dependencies]
anyhow = "1"
num-complex = "0.4.6"
symbolica = { version = "1.3" }
symjit = { version = "2.13.0", path = "../symjit-crate"  }
wide = "0.8"

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "symjit_bridge"
path = "src/bin.rs"
